name: Bug Report
description: File a bug report to help us improve Permit.Phoenix
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - vincentvanbush

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: input
    id: permit-phoenix-version
    attributes:
      label: Permit.Phoenix version
      description: What version of Permit.Phoenix are you using?
      placeholder: e.g., 0.3.0
    validations:
      required: true

  - type: input
    id: permit-version
    attributes:
      label: Permit version
      description: What version of core Permit are you using?
      placeholder: e.g., 0.3.0
    validations:
      required: true

  - type: input
    id: permit-ecto-version
    attributes:
      label: Permit.Ecto version (if used)
      description: If using database integration, what version of Permit.Ecto?
      placeholder: e.g., 0.2.4

  - type: input
    id: elixir-version
    attributes:
      label: Elixir/OTP version
      description: What version of Elixir and OTP are you using?
      placeholder: e.g., Elixir 1.17.0, OTP 27
    validations:
      required: true

  - type: input
    id: phoenix-version
    attributes:
      label: Phoenix/LiveView version
      description: What version of Phoenix and LiveView are you using?
      placeholder: e.g., Phoenix 1.7.0, LiveView 0.20.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Set up Phoenix controller with...
        2. Define permissions as...
        3. Access the route...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code sample
      description: Please provide a minimal code example that demonstrates the issue
      render: elixir
      placeholder: |
        # Controller setup
        defmodule MyAppWeb.ArticleController do
          use Permit.Phoenix.Controller,
            authorization_module: MyApp.Authorization,
            resource_module: MyApp.Article

          def show(conn, _params) do
            # Your code here
          end
        end

        # Or LiveView setup
        defmodule MyAppWeb.ArticleLive do
          use Permit.Phoenix.LiveView,
            authorization_module: MyApp.Authorization,
            resource_module: MyApp.Article
        end

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened? Include error messages if any.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs/stack trace
      description: If applicable, add error logs or stack traces
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here (router setup, LiveView hooks, database setup, etc.)

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have provided all the requested information
          required: true
        - label: This is a bug report, not a feature request or question. For general questions, please use [Elixir Slack's Permit channel](https://elixir-lang.slack.com/archives/C091Q5S0GDU).
          required: true
