name: Feature Request
description: Suggest a new feature or enhancement for Permit.Phoenix
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - vincentvanbush

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: Is your feature request related to a Phoenix/LiveView usage pattern you've identified as needing improvement? Please describe.
      placeholder: I've noticed that often when working with Phoenix controllers... / I'm always frustrated when using LiveView authorization...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to be able to authorize Phoenix actions by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I have also considered using custom plugs... / I tried implementing this with LiveView hooks...

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe your specific Phoenix/LiveView use case and how this feature would help
      placeholder: In my Phoenix application, I need to authorize controller actions that... / My LiveView needs to handle authorization for...
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Desired API/code example
      description: If possible, show what the API or code usage would look like
      render: elixir
      placeholder: |
        # Example of how you'd like to use this feature in a controller
        defmodule MyAppWeb.ArticleController do
          use Permit.Phoenix.Controller,
            authorization_module: MyApp.Authorization,
            resource_module: MyApp.Article,
            new_feature: :some_option

          def show(conn, _params) do
            # Enhanced functionality here
          end
        end

        # Or in a LiveView
        defmodule MyAppWeb.ArticleLive do
          use Permit.Phoenix.LiveView,
            authorization_module: MyApp.Authorization,
            resource_module: MyApp.Article

          @impl true
          def handle_event("new_action", _params, socket) do
            # New authorization pattern here
          end
        end

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component of Permit.Phoenix does this relate to?
      options:
        - Controllers
        - LiveView
        - Router Integration
        - Error Handling
        - Action Mapping
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (1-3)
      description: How important is this feature to you?
      options:
        - 1 - Low - Nice to have
        - 2 - Medium - Would be helpful
        - 3 - High - Blocking my work
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have checked the roadmap in the README
          required: true
        - label: This is a feature request, not a bug report or question. For general questions, please use [Elixir Slack's Permit channel](https://elixir-lang.slack.com/archives/C091Q5S0GDU).
          required: true
